### ISSUE TITLE
Fazer readme em portugues

### ISSUE THREAD

**Issue by nascimento-felipe** [filipe-muniz/dsa-typescript#1]
Boa noite Sr. Dr. Filipe Muniz.

O que acha de fazer um readme em portugues? viro gringo pra ficar mandando leiame em ingles??

tamo junto

**Comment by filipe-muniz** [comment]
É professor doutor pra você >.<

**Comment by wesleyterrao** [comment]
foi só terminar o doutorado que começou...

**Comment by nascimento-felipe** [comment]
Desculpe, Professor Doutor Filipe Muniz.

Deixe de ser o cartoonizando e odiar brasileiros. >:c
